# Generated by Django 3.0.5 on 2020-04-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=140)),
                ('book', models.TextField()),
                ('image', models.ImageField(upload_to='book/')),
            ],
        ),
    ]
