# Generated by Django 3.0.5 on 2020-04-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
